# version: '3.9'

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:sungmiki
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_network
    restart: always
      

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:sungmiki
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wp_content:/var/www/html/
    networks:
      - wp_network
    restart: always

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:sungmiki
    depends_on:
      - wordpress
    volumes:
      - wp_content:/var/www/html/
    ports:
      - "443:443"
    networks:
      - wp_network
    restart: always

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/sungmiki/data/mariadb
      o: bind
  wp_content:
    driver: local
    driver_opts:
      type: none
      device: /home/sungmiki/data/wordpress
      o: bind

networks:
  wp_network:
    driver: bridge
