# version: '3.9'

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      # args:
      #   ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      #   DB_NAME: ${DB_NAME}
      #   DB_USER: ${DB_USER}
      #   DB_PASSWORD: ${DB_PASSWORD}
    image: mariadb:sungmiki.v1.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /home/sungmiki/data/mariadb:/var/lib/mysql
    networks:
      - wp_network
    restart: always
      

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:sungmiki.v1.0
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /home/sungmiki/data/wordpress:/var/www/html
    networks:
      - wp_network
    restart: always

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:sungmiki.v1.0
    depends_on:
      - wordpress
    volumes:
      - /home/sungmiki/data/wordpress:/usr/share/nginx/html
      # - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
    networks:
      - wp_network
    restart: always

# volumes:
#   db_data:
#   wp_content:

networks:
  wp_network:
